name: build-push

on:
  push:
    branches:
      - v*
  workflow_dispatch:

jobs:
  docker:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Set env.FOAM_VERSION
        run: |
          echo "FOAM_VERSION=${GITHUB_REF#refs/heads/v}" >> "$GITHUB_ENV"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build '-run' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ env.FOAM_VERSION }}
          file: openfoam-run_leap.Dockerfile
          context: .
          platforms: linux/arm64
          load: true
          tags: gerlero/openfoam-run:${{ env.FOAM_VERSION }}
      -
        name: Test '-run' image
        run: |
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -run -- foamInstallationTest
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -run -- icoFoam -help
        shell: 'script -q -e -c "bash -e {0}"'
      -
        name: Push '-run' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ env.FOAM_VERSION }}
          file: openfoam-run_leap.Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: gerlero/openfoam-run:${{ env.FOAM_VERSION }}
      -
        name: Build '-dev' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ env.FOAM_VERSION }}
          file: openfoam-dev_leap.Dockerfile
          context: .
          platforms: linux/arm64
          load: true
          tags: gerlero/openfoam-dev:${{ env.FOAM_VERSION }}
      -
        name: Test '-dev' image
        run: |
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -dev -- foamInstallationTest
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -dev -- icoFoam -help
        shell: 'script -q -e -c "bash -e {0}"'
      -
        name: Push '-dev' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ env.FOAM_VERSION }}
          file: openfoam-dev_leap.Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: gerlero/openfoam-dev:${{ env.FOAM_VERSION }}
      -
        name: Build '-default' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ env.FOAM_VERSION }}
          file: openfoam-default_leap.Dockerfile
          context: .
          platforms: linux/arm64
          load: true
          tags: gerlero/openfoam-default:${{ env.FOAM_VERSION }}
      -
        name: Test '-default' image
        run: |
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -default -- foamInstallationTest
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -default -- icoFoam -help
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -default -- foamTestTutorial -full incompressible/simpleFoam/pitzDaily
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -default -- foamTestTutorial -full -parallel basic/laplacianFoam/flange
        shell: 'script -q -e -c "bash -e {0}"'
      -
        name: Push '-default' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ env.FOAM_VERSION }}
          file: openfoam-default_leap.Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: gerlero/openfoam-default:${{ env.FOAM_VERSION }}
