name: Build images

on:
  push:
    branches:
      - 'v*'
  workflow_call:
    inputs:
      openfoam-version:
        type: string
        required: true
      push:
        type: boolean
        required: false
        default: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set env.FOAM_VERSION from branch name
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/v') }}
        run: |
          echo "FOAM_VERSION=${GITHUB_REF#refs/heads/v}" >> "$GITHUB_ENV"
      - name: Set env.FOAM_VERSION from workflow input
        if: ${{ github.event_name != 'push' || !startsWith(github.ref, 'refs/heads/v') }}
        run: |
          echo "FOAM_VERSION=${{ inputs.openfoam-version }}" >> "$GITHUB_ENV"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/v') || inputs.push }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build '-run' image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            OS_VER=${{ env.FOAM_VERSION <= 2012 && '20.04' || '22.04'}}
            FOAM_VERSION=${{ env.FOAM_VERSION }}
          target: run
          platforms: linux/arm64
          load: true
          tags: gerlero/openfoam-run:${{ env.FOAM_VERSION }}
      - name: Check '-run' image
        run: |
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -run -- foamInstallationTest
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -run -- icoFoam -help
        shell: 'script -q -e -c "bash -e {0}"'
      - name: Build '-dev' image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            OS_VER=${{ env.FOAM_VERSION <= 2012 && '20.04' || '22.04'}}
            FOAM_VERSION=${{ env.FOAM_VERSION }}
          target: dev
          platforms: linux/arm64
          load: true
          tags: gerlero/openfoam-dev:${{ env.FOAM_VERSION }}
      - name: Check '-dev' image
        run: |
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -dev -- foamInstallationTest
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -dev -- icoFoam -help
        shell: 'script -q -e -c "bash -e {0}"'
      - name: Build '-default' image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            OS_VER=${{ env.FOAM_VERSION <= 2012 && '20.04' || '22.04'}}
            FOAM_VERSION=${{ env.FOAM_VERSION }}
          target: default
          platforms: linux/arm64
          load: true
          tags: gerlero/openfoam-default:${{ env.FOAM_VERSION }}
      - name: Check '-default' image
        run: |
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -default -- foamInstallationTest
          ./openfoam-docker-arm -${{ env.FOAM_VERSION }} -default -- icoFoam -help
        shell: 'script -q -e -c "bash -e {0}"'
      - name: Push images
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/v') || inputs.push }}
        run: |
          docker push gerlero/openfoam-run:${{ env.FOAM_VERSION }}
          docker push gerlero/openfoam-dev:${{ env.FOAM_VERSION }}
          docker push gerlero/openfoam-default:${{ env.FOAM_VERSION }}
