name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: OpenFOAM v${{ matrix.foam_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        foam_version:
          - '2112'
          - '2106'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build '-run' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ matrix.foam_version }}
          file: openfoam-run_leap.Dockerfile
          context: .
          platforms: linux/arm64
          load: true
          tags: gerlero/openfoam${{ matrix.foam_version }}-run
      -
        name: Test '-run' image
        run: |
          ./openfoam-docker-arm -${{ matrix.foam_version }} -run -- foamInstallationTest
          ./openfoam-docker-arm -${{ matrix.foam_version }} -dev -- icoFoam -help
        shell: 'script -q -e -c "bash -e {0}"'
      -
        name: Push '-run' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ matrix.foam_version }}
          file: openfoam-run_leap.Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: gerlero/openfoam${{ matrix.foam_version }}-run
      -
        name: Build '-dev' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ matrix.foam_version }}
          file: openfoam-dev_leap.Dockerfile
          context: .
          platforms: linux/arm64
          load: true
          tags: gerlero/openfoam${{ matrix.foam_version }}-dev
      -
        name: Test '-dev' image
        run: |
          ./openfoam-docker-arm -${{ matrix.foam_version }} -dev -- foamInstallationTest
          ./openfoam-docker-arm -${{ matrix.foam_version }} -dev -- icoFoam -help
        shell: 'script -q -e -c "bash -e {0}"'
      -
        name: Push '-dev' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ matrix.foam_version }}
          file: openfoam-dev_leap.Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: gerlero/openfoam${{ matrix.foam_version }}-dev
      -
        name: Build '-default' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ matrix.foam_version }}
          file: openfoam-default_leap.Dockerfile
          context: .
          platforms: linux/arm64
          load: true
          tags: gerlero/openfoam${{ matrix.foam_version }}-default
      -
        name: Test '-default' image
        run: |
          ./openfoam-docker-arm -${{ matrix.foam_version }} -default -- foamInstallationTest
          ./openfoam-docker-arm -${{ matrix.foam_version }} -default -- icoFoam -help
          ./openfoam-docker-arm -${{ matrix.foam_version }} -default -- foamTestTutorial -full incompressible/simpleFoam/pitzDaily
          ./openfoam-docker-arm -${{ matrix.foam_version }} -default -- foamTestTutorial -full -parallel basic/laplacianFoam/flange
        shell: 'script -q -e -c "bash -e {0}"'
      -
        name: Push '-default' image
        uses: docker/build-push-action@v2
        with:
          build-args: FOAM_VERSION=${{ matrix.foam_version }}
          file: openfoam-default_leap.Dockerfile
          context: .
          platforms: linux/arm64
          push: true
          tags: gerlero/openfoam${{ matrix.foam_version }}-default
